### ISSUE TITLE
StopActions cannot be found, appears to be StopCommands

### ISSUE THREAD

**Issue by jberndsen** [WasabiFan/ev3dev-lang-js#20]
Whilst attempting to run the example scripts utilizing a Motor, an error is thrown that the StopActions file cannot be found. When looking for the missing file, it turns out to be indeed not there, but rather there is a StopCommands file which seems to be the right one.

Is there perhaps a mismatch between ev3dev version and this language binding? Is there a way I can work around this or help to fix it?

**Comment by WasabiFan** [comment]
What's the output of `uname -r`? `stop_command` was renamed to `stop_action` in the kernel to eliminate confusion with normal `command`s in one of the more recent kernel versions. This was after the most recent image release (the one from December). So, if the output of that command says that your kernel is older than `*-11-ev3dev-*`, you will want to upgrade your kernel.

If you need to upgrade, assuming your EV3/other ev3dev device has internet access, you can upgrade the kernel as follows:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```

**This will likely take an hour or more.** If you don't want to wait that long, you can also re-flash your SD card with a nightly image that includes the newest kernel (re-flashing will erase all files that you have created). You can get the most recent nightly from here:

[ ![Download](https://api.bintray.com/packages/ev3dev/nightly/ev3dev-jessie/images/download.svg) ](https://bintray.com/ev3dev/nightly/ev3dev-jessie/_latestVersion)

**Comment by jberndsen** [comment]
This was exactly it, thanks so much. I've got my very first Javascript powered motor running.

**Comment by WasabiFan** [comment]
Great! Glad to hear that it worked. If you run into any other issues, don't hesitate to ask.
