### ISSUE TITLE
Not downloaded

### ISSUE THREAD

**Issue by Konlll** [WasabiFan/ev3dev-lang-js#23]
**Dear @WasabiFan !**

When I downloaded this repository, it didn't download the docs folder.

Do you help?

**Comment by WasabiFan** [comment]
The docs directory contents can be found in this branch: https://github.com/WasabiFan/ev3dev-lang-js/tree/gh-pages

**Comment by Konlll** [comment]
Ok, thank you!

2018. jan. 5. 23:30 ezt írta ("Kaelin Laundry" <notifications@github.com>):
