### ISSUE TITLE
Commands are verbs and should map to functions

### ISSUE THREAD

**Issue by nathanboktae** [WasabiFan/ev3dev-lang-js#8]
Let's look at the sentence "Rotate 90 degrees at half power and then stop":

```
(S (S (VP Rotate
          (NP 90 degrees)
          (PP at
              (NP half))))
   power and
   (S (VP (ADVP then)
          stop)))
```

It starts out with verbs, with are associated with noun phrases and verb phrases. It's an action; a command to something, like a tacho-motor. It's not an object, or noun.

Yet your example for this is to [set a bunch of properties on an object](https://github.com/WasabiFan/ev3dev-lang-js/blob/679078632fb8424d41f74ace523a9151dff3c47a/examples/run-specific-motor.js#L9-L13):

``` javascript
motor.positionSp = 180;
motor.speedSp = 500;
motor.stopCommand = 'brake';
motor.command = "run-to-rel-pos";
```

rather than calling a function (method) like this:

``` javascript
motor.runToRelativePosition(180, 500, 'brake')
```

Please let's use functions here. It's the cleaner, sane way to interact with the motors and sensors.

**Comment by WasabiFan** [comment]
Although I agree that these commands _should_ be invoke-able as functions for optimal usability, in practice I simply haven't had time to do much to improve this library recently. I am very busy with "real life", so without seeing any signs that people were using my code I didn't see a reason to push up the priority and get it done soon. I already have a note in #4 that this is a feature that I need to add.

As it stands, this library is a direct wrapper of ev3dev's file-system APIs, hence the peculiar `command = ...` idioms. The enhanced usability makes it much easier to use but you can still access all functionality through the setter interfaces that already exist.

I already have some of these methods implemented for motors [here](https://github.com/WasabiFan/ev3dev-lang-js/blob/develop/src/motors.ts#L456-L512) -- I suspect that that's mainly what you are looking for. So yes, it's a feature that I plan to add; but that requires time that I don't have at the moment. I'll see if I can get this done in a few days/weeks, but as always PRs are welcome!

P.S. The tone of your post makes me think that something else has frustrated you with this code -- are the docs for existing functionality lacking, or is it something else that's making it difficult?

**Comment by nathanboktae** [comment]
> I am very busy with "real life"

That's fine. I understand as I maintain OSS projects too.

> I already have some of these methods implemented for motors here ... but as always PRs are welcome!

Oh great! I didn't see those, I'll submit a PR to update the examples.

> The tone of your post makes me think that something else has frustrated you with this code

Yeah I'm an ex-Microsoftie who has learned functional programming and unlearned bad patterns in OOP thanks to a few key smart coworkers to help me, so I want to help others break out of the "everything is an object" and nouns and take a higher look at things. [Execution in the Kingdom of Nouns](http://steve-yegge.blogspot.com/2006/03/execution-in-kingdom-of-nouns.html) is a fun read and while ranty has some good higher level points.

Yes I do realize `motor.runToRelativePosition(180, 500, 'brake')` is standard method call on a class, but other improvements would be nice along this line, like a callback when the run is done (I know that requires polling internally, but that would be a nice interface) ala node style (or even better, return a promise).

**Comment by WasabiFan** [comment]
I just added some new helpers to the motor class and updated the examples to use them.

Besides the ones that are currently implemented, what helper methods would you like to see added for commands/modes? I currently just have these functions added for tacho motors, so I think a good first step would be for me to add them for servos and DC motors.

**Comment by nathanboktae** [comment]
This is great. Yes I think adding similar methods for servos and DCs makes sense.

**Comment by nathanboktae** [comment]
Honestly though playing around with it more I'll probably use Go as node.js is so slow on the EV3. look at this rediculousness:

```
robot@ev3dev:~/node-ex$ echo console.log\(1\) > dummy.js
robot@ev3dev:~/node-ex$ time node dummy.js
1

real    0m20.662s
user    0m5.060s
sys 0m0.250s
```

TWENTY second startup time. I've already started reading twitter by then.... and now I'm not coding my lego robot :P

**Comment by WasabiFan** [comment]
Ha yeah... The start time is pretty terrible. I generally don't see 20 seconds, but 5-10 is fairly common. I maintain this library mainly in case people want to write servers or other async systems, which is what Node is good at; for most other stuff, I'd recommend using Python or another language.

**Comment by nathanboktae** [comment]
Yeah I was seeing 5-10sec the other day, but now it's crazy slow? Yeah I love node (I write Node.js APIs at work (koa)), but Go channels should be nice here too.

Is Python a lot faster than Node on the ev3? Go will go down to a binary and I could even cross-compile it then scp it over if needed.
